#!/bin/bash
# INSTRUCCIONES PARA CONFIGURAR LAS TABLAS EN SUPABASE

echo "=================================================="
echo "PASOS PARA CREAR LAS TABLAS EN SUPABASE"
echo "=================================================="
echo ""
echo "1. Ve a tu proyecto en supabase.com"
echo "2. Haz click en 'SQL Editor' en la barra lateral"
echo "3. Haz click en '+ New Query'"
echo "4. Copia TODO el contenido de: SUPABASE_TABLES.txt"
echo "5. Pégalo en el editor SQL"
echo "6. Haz click en 'Run' (botón verde con ▶)"
echo ""
echo "Si ves errores como 'relation already exists',"
echo "significa que las tablas ya existen, eso es OK."
echo ""
echo "=================================================="
echo "TABLAS CREADAS:"
echo "=================================================="
echo ""
echo "✅ assignment_submissions"
echo "   - Almacena las entregas de estudiantes"
echo "   - Campos: id, assignment_id, student_id, screenshot_url, submitted_at"
echo ""
echo "✅ assignment_submissions_grades"
echo "   - Almacena las calificaciones"
echo "   - Campos: id, submission_id, assignment_id, teacher_id, score, feedback, graded_at"
echo ""
echo "✅ 5 Índices para optimizar consultas"
echo ""
echo "=================================================="
echo "CONFIGURACIÓN DE RLS (SEGURIDAD)"
echo "=================================================="
echo ""
echo "Importante: Si tienes RLS habilitado, configura:"
echo ""
echo "1. Para assignment_submissions:"
echo "   - SELECT: Los estudiantes pueden ver sus propias entregas"
echo "   - INSERT: Los estudiantes pueden crear entregas"
echo ""
echo "2. Para assignment_submissions_grades:"
echo "   - SELECT: Los profesores pueden ver calificaciones"
echo "   - INSERT: Los profesores pueden crear calificaciones"
echo "   - UPDATE: Los profesores pueden actualizar calificaciones"
echo ""
echo "=================================================="
echo "VERIFICACIÓN"
echo "=================================================="
echo ""
echo "Después de ejecutar, verifica en Supabase:"
echo "1. Ve a 'Table Editor'"
echo "2. Deberías ver:"
echo "   - assignment_submissions"
echo "   - assignment_submissions_grades"
echo ""
echo "¡Listo! Las tablas están configuradas."
echo ""
